version: "3.8"

services:
  api_rac:
    build: .
    container_name: api_rac
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
      - ./persist/config.json:/app/dist/config/config.json
    environment:
      - NODE_ENV=production
      - PORT=3000
      - EGESTOR_API_URL=https://api.egestor.com.br/api
    restart: always
    networks:
      - app_net

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api_rac
    networks:
      - app_net

networks:
  app_net:
    driver: bridge